#include "Accipiter_gundlachi.h"
#include "stdafx.h"

void Accipiter_gundlachi::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8F begin
{
	printf("\nspeed: to 70 km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Accipiter_gundlachi::spread_wings()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C95 begin
{
	printf("\nspread wings.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C95 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Accipiter_gundlachi::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9B begin
{
	printf("\nvoice: kyik-kyik.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Accipiter_gundlachi::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8F begin
{
	return "Accipiter_gundlachi";
}

double Accipiter_gundlachi::get_wingspan() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8F begin
{
	return 75.3;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Accipiter_gundlachi::print()
{
	printf("\nwingspan: %.1fc.\n", get_wingspan());
}
