#include "Anseriformes.h"
#include "stdafx.h"

/*Гусеобразные*/
void Anseriformes::swim()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BDC begin
{
	printf("\nswim.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BDC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Anseriformes::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BDE begin
{
	printf("\nvoice: Gha-gha-gha.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BDE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Anseriformes::get_weight() const {
	return 1.6;
}

char * Anseriformes::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BDE begin
{
	return "Anseriformes";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BDE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
