#include "Apteryx_owenii.h"
#include "stdafx.h"

/*Малый киви*/
void Apteryx_owenii::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AC9 begin
{
	printf("\nvoice: eeay-eeay.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AC9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Apteryx_owenii::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Apteryx_owenii";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Apteryx_owenii::get_weight() const {
	return 1.3;
}

double Apteryx_owenii::get_size_egg() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 0.8;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Apteryx_owenii::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nsize egg: %.1fc.\n", get_size_egg());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element