#include "Apteryx_australis.h"
#include "stdafx.h"

/*обыкновенный киви*/
void Apteryx_australis::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AC7 begin
{
	printf("\nvoice: eay-eay-eay.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AC7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Apteryx_australis::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AC7 begin
{
	return "Apteryx_australis";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AC7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Apteryx_australis::get_weight() const {
	return 3.1;
}

double Apteryx_australis::get_size_egg() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 1.1;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Apteryx_australis::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nsize egg: %.1fc.\n", get_size_egg());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element