#include "Aquila_nipalensis.h"
#include "stdafx.h"

/*Степной орёл*/
void Aquila_nipalensis::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CE6 begin
{
	printf("speed: to 190km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CE6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Aquila_nipalensis::spread_wings()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CEA begin
{
	printf("\nspread wings.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CEA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Aquila_nipalensis::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CEE begin
{
	printf("\nvoice: ia-ia.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CEE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Aquila_nipalensis::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Aquila_chrysaetos";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Aquila_nipalensis::get_wingspan() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 190.1;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Aquila_nipalensis::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nwingspan: %.1fc.\n", get_wingspan());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element