#include "Aquila_chrysaetos.h"
#include "stdafx.h"

/*Беркут*/
void Aquila_chrysaetos::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CE4 begin
{
	printf("\nspeed: to 300km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CE4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Aquila_chrysaetos::spread_wings()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CE8 begin
{
	printf("\nspread wings.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CE8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Aquila_chrysaetos::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CEC begin
{
	printf("\nvoice: ia-ia.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CEC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Aquila_chrysaetos::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Aquila_chrysaetos";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Aquila_chrysaetos::get_wingspan() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 200.3;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Aquila_chrysaetos::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nwingspan: %.1fc.\n", get_wingspan());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element