#include "Columbiformes.h"
#include "stdafx.h"

/*Голубеобразные*/
void Columbiformes::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BD6 begin
{
	printf("\nspeed: to 100km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BD6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

/*клевать*/
void Columbiformes::peck()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BD8 begin
{
	printf("\npeck.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BD8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Columbiformes::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BDA begin
{
	printf("\nvoice: сurlew-curlew.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BDA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Columbiformes::get_weight() const {
	return 0.4;
}

char * Columbiformes::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Columbiformes";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element