#include "Cuculiformes.h"
#include "stdafx.h"

/* укушкообразные*/
void Cuculiformes::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BE2 begin
{
	printf("\nspeed: to 30km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BE2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

/*отложить €йцо*/
void Cuculiformes::lay_egg()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BE4 begin
{
	printf("\nto lay an egg.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BE4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

/*свить гнездо*/
void Cuculiformes::buail_nest()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BE6 begin
{
	printf("\nbuild a nest.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BE6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cuculiformes::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BE8 begin
{
	printf("\nvoice: ku-ku.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BE8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Cuculiformes::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Cuculiformes";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element