#include "Diomedeidae.h"
#include "stdafx.h"

/*Альбатросы */
/*есть рыбу*/
void Diomedeidae::eat_fish()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B64 begin
{
	printf("\neat fish.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B64 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
