#include "Diomedea_amsterdamensis.h"
#include "stdafx.h"

/*Амстердамский альбатрос */
void Diomedea_amsterdamensis::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B75 begin
{
	printf("\nvoice: ua-ua.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B75 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Diomedea_amsterdamensis::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CF1 begin
{
	printf("\nspeed: to 50km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CF1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Diomedea_amsterdamensis::get_lenght_beak() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 6.6;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Diomedea_amsterdamensis::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nlenght beak: %.1fc.\n", get_lenght_beak());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Diomedea_amsterdamensis::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Diomedea_amsterdamensis";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element