#include "Dromaius_novaehollandiae.h"
#include "stdafx.h"

/*Ёму*/
void Dromaius_novaehollandiae::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000ABF begin
{
	printf("\nvoice: ur-ur.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000ABF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

/*идти вперед*/
void Dromaius_novaehollandiae::go_ahead()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AC1 begin
{
	printf("\ngo ahead.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AC1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Dromaius_novaehollandiae::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Dromaius_novaehollandiae";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Dromaius_novaehollandiae::get_weight() const
{
	return 0.7;
}

double Dromaius_novaehollandiae::get_size_egg() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 10.1;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Dromaius_novaehollandiae::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nsize egg: %.1fc.\nweight: %.1fkg.", get_size_egg(), get_weight());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element