#include "Dryocopus javensis.h"
#include "stdafx.h"

/*Белобрюхая желна */
void Dryocopus_javensis::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C2E begin
{
	printf("\nvoice: ikii-ikii.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C2E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Dryocopus_javensis::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CFF begin
{
	printf("\nspeed: to 35km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CFF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Dryocopus_javensis::get_color() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 2;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Dryocopus_javensis::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Dryocopus_javensis";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Dryocopus_javensis::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\ncolor: white.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element