#include "Falco_peregrinus.h"
#include "stdafx.h"

/*Сапсан*/
void Falco_peregrinus::spread_wings()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C53 begin
{
	printf("\nspread wings.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C53 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Falco_peregrinus::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C5B begin
{
	printf("\nvoice: kwik.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C5B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Falco_peregrinus::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C87 begin
{
	printf("\nspeed: to 250km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C87 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Falco_peregrinus::get_wingspan() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 120.8;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Falco_peregrinus::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Falco_peregrinus";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Falco_peregrinus::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nwingspan: %.1fc.\n", get_wingspan());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element