#include "Galliformes.h"
#include "stdafx.h"

/*Курообразные */
void Galliformes::lay_egg()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BEA begin
{
	printf("\nto lay an egg.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BEA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Galliformes::get_weight() const {
	return 1.2;
}

char * Galliformes::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Galliformes";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Galliformes::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BEC begin
{
	printf("\nvoice: kudah-kudah.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BEC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
