#include "Gyps_fulvus.h"
#include "stdafx.h"

/*Белоголовый сип */
void Gyps_fulvus::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CAF begin
{
	printf("\nspeed: to 45km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CAF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Gyps_fulvus::spread_wings()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CB5 begin
{
	printf("\nspread wings.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CB5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Gyps_fulvus::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CBB begin
{
	printf("\nvoice: kyy-kyy.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000CBB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Gyps_fulvus::get_wingspan() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 230.2;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Gyps_fulvus::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Gyps_fulvus";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Gyps_fulvus::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nwingspan: %.1fc.\n", get_wingspan());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element