#include "Palaeognathae.h"
#include "stdafx.h"
/*Бескилевые*/

/*бежать*/
void Palaeognathae::run()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000A7B begin
{
	printf("Runing");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000A7B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
