#include "Passeriformes.h"
#include "stdafx.h"
/*воробьинообразные*/


void Passeriformes::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BD0 begin
{
	printf("\nspeed: to 38km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BD0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Passeriformes::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BD2 begin
{
	printf("\nvoice: chiric-chiric.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BD2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Passeriformes::get_weight() const {
	return 0.02;
}

char * Passeriformes::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Passeriformes";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

/*прыгать*/
void Passeriformes::jump()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BD4 begin
{
	printf("\njump.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BD4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
