#include "Procellariiformes.h"
#include "stdafx.h"
/*буревестикообразные*/


/*открыть клюв*/
void Procellariiformes::open_beak()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B5A begin
{
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B5A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
