#include "Pterodroma_hasitata.h"
#include "stdafx.h"
/*Черношапочный тайфунник*/


void Pterodroma_hasitata::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B9E begin
{
	printf("\nspeed: to 43km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B9E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Pterodroma_hasitata::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BAD begin
{
	printf("\nvoice: ruuua-ruuua.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BAD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Pterodroma_hasitata::get_lenght_beak() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 17.4;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Pterodroma_hasitata::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Pterodroma_hasitata";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Pterodroma_hasitata::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nwingspan: %.1fc.\n", get_lenght_beak());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element