#include "Pterodroma_hypoleuca.h"
#include "stdafx.h"
/*Бонинский тайфунник*/


void Pterodroma_hypoleuca::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B9C begin
{
	printf("\nspeed: to 80km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B9C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Pterodroma_hypoleuca::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BAB begin
{
	printf("\nvoice: ruua-ruua.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BAB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Pterodroma_hypoleuca::get_lenght_beak() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 12.3;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Pterodroma_hypoleuca::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Pterodroma_hypoleuca";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Pterodroma_hypoleuca::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nlenght beak: %.1fc.\n", get_lenght_beak());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element