#include "Pterodroma_cahow.h"
#include "stdafx.h"
/*Бермудский тайфунник*/



void Pterodroma_cahow::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B9A begin
{
	printf("\nspeed: to 40km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000B9A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Pterodroma_cahow::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BA9 begin
{
	printf("\nvoice: rua-rua.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BA9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Pterodroma_cahow::get_lenght_beak() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 15.8;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Pterodroma_cahow::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Pterodroma_cahow";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Pterodroma_cahow::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nwingspan: %.1fc.\n", get_lenght_beak());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element