#include "Rhea americana.h"
#include "stdafx.h"
/*Cеверный нанду*/

/*высижывать €йцо*/
void Rhea_americana::hatch_egg()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AD0 begin
{
	printf("\nto hatch an egg.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AD0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Rhea_americana::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AD2 begin
{
	printf("\nvoice: uu-uu.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AD2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Rhea_americana::get_weight() const {
	return 25;
}

double Rhea_americana::get_size_egg() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 1.3;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Rhea_americana::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Rhea_americana";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Rhea_americana::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nsize egg: %.1fc.\n", get_size_egg());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element