#include "Semnornis frantzii.h"
#include "stdafx.h"
/*«убчатоклювый туканий бородастик*/


void Semnornis_frantzii::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C10 begin
{
	printf("\nvoice: ik-ik.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C10 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Semnornis_frantzii::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8D begin
{
	printf("\nspeed: to 280km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Semnornis_frantzii::get_color() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8B begin
{
	return 134;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Semnornis_frantzii::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Semnornis_frantzii";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Semnornis_frantzii::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8B begin
{
	printf("\ncolor: black, yellow, red.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element