#include "Semnornis ramphastinus.h"
#include "stdafx.h"
/*Туканий бородастик */


void Semnornis_ramphastinus::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C12 begin
{
	printf("\nvoice: iik-iik.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C12 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Semnornis_ramphastinus::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8B begin
{
	printf("\nspeed: to 310km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Semnornis_ramphastinus::get_color() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8B begin
{
	return 4;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Semnornis_ramphastinus::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Semnornis_ramphastinus";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Semnornis_ramphastinus::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8B begin
{
	printf("\ncolor: yellow.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C8B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element