#include "Striges.h"
#include "stdafx.h"
/*Совообразные*/


/*поймать мышь*/
void Striges::catch_mouse()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BEE begin
{
	printf("\ncatch mouse.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BEE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Striges::fly()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BF0 begin
{
	printf("\nspeed: to 400km/h.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BF0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

/*плавать*/
void Striges::swim()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BF2 begin
{
	printf("\nswim.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BF2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

/*повернуть голову на 180 градусов*/
void Striges::turn_head180()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BF4 begin
{
	printf("\nturn head 180.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BF4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Striges::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Striges";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Striges::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BF6 begin
{
	printf("\nuuh-uuh.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000BF6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
