#include "Struthio_Camelus.h"
#include "stdafx.h"
/*Страус*/

/*отложить яйцо*/
void Struthio_Camelus::lay_egg()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AE5 begin
{
	printf("\nto lay an egg.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AE5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Struthio_Camelus::voice()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AE7 begin
{
	printf("\nvoice: uuu-uuu.\n");
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000AE7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char * Struthio_Camelus::type() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return "Struthio_Camelus";
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Struthio_Camelus::get_weight() const {
	return 150;
}

double Struthio_Camelus::get_size_egg() const
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	return 20.4;
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Struthio_Camelus::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D begin
{
	printf("\nsize egg: %.1fc.\n", get_size_egg());
}
// section -84-16-6-55-5c5b142f:1577a6d9169:-8000:0000000000000C9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element